### ISSUE TITLE
红米AX6拉取编译后，设置到160hz搜不到无线信号。

### ISSUE THREAD

**Issue by jarod360** [Boos4721/openwrt#1]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
红米AX6拉取编译后，设置到160hz搜不到无线信号。
Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：红米 AX6

### (3) 详细日志

A：

**Comment by Boos4721** [comment]
> 都是给AX3600的优化 你要开的话信道设置44等一分钟

**Comment by jarod360** [comment]
好的，谢谢大佬。

**Comment by jarod360** [comment]
老大在线编译的时候，Download package会出现下列报错。但是编译也没任何影响。编译出来的固件好像使用也没啥问题。不知道是不是我的配置文件的问题，还是什么造成的。
tmp/.config-package.in:112526:error: recursive dependency detected!
tmp/.config-package.in:112526:	symbol PACKAGE_wrtbwmon depends on BUSYBOX_DEFAULT_IP
package/utils/busybox/Config-defaults.in:2367:	symbol BUSYBOX_DEFAULT_IP depends on PACKAGE_busybox
tmp/.config-package.in:143:	symbol PACKAGE_busybox is selected by PACKAGE_wrtbwmon
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

tmp/.config-package.in:92621:error: recursive dependency detected!
tmp/.config-package.in:92621:	symbol PACKAGE_iptables is selected by PACKAGE_ip-full
tmp/.config-package.in:99192:	symbol PACKAGE_ip-full is selected by PACKAGE_luci-app-passwall
tmp/.config-package.in:67312:	symbol PACKAGE_luci-app-passwall depends on PACKAGE_iptables
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

**Comment by Boos4721** [comment]
> 老大在线编译的时候，Download package会出现下列报错。但是编译也没任何影响。编译出来的固件好像使用也没啥问题。不知道是不是我的配置文件的问题，还是什么造成的。
> tmp/.config-package.in:112526:error: recursive dependency detected!
> tmp/.config-package.in:112526: symbol PACKAGE_wrtbwmon depends on BUSYBOX_DEFAULT_IP
> package/utils/busybox/Config-defaults.in:2367: symbol BUSYBOX_DEFAULT_IP depends on PACKAGE_busybox
> tmp/.config-package.in:143: symbol PACKAGE_busybox is selected by PACKAGE_wrtbwmon
> For a resolution refer to Documentation/kbuild/kconfig-language.rst
> subsection "Kconfig recursive dependency limitations"
> 
> tmp/.config-package.in:92621:error: recursive dependency detected!
> tmp/.config-package.in:92621: symbol PACKAGE_iptables is selected by PACKAGE_ip-full
> tmp/.config-package.in:99192: symbol PACKAGE_ip-full is selected by PACKAGE_luci-app-passwall
> tmp/.config-package.in:67312: symbol PACKAGE_luci-app-passwall depends on PACKAGE_iptables
> For a resolution refer to Documentation/kbuild/kconfig-language.rst
> subsection "Kconfig recursive dependency limitations"

不影响使用

**Comment by jarod360** [comment]
谢了大佬
